// AUTOGENERATED by packages/release (bun run release:daemon) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored bundle outputs): this pins the
// published daemon release that the cloud's /api/daemon/binary route redirects
// to. Re-run `bun run release:daemon`, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release script run fills in the tag + checksums.

import type { TDaemonRelease } from "./release-types";

export const DAEMON_RELEASE: TDaemonRelease = {
  repo: "openllmsh/daemon",
  tag: "v2.7.10-alpha.1",
  targets: [
    "darwin-arm64",
    "darwin-x64-baseline",
    "linux-x64-baseline",
    "linux-arm64",
  ],
  sha256: {
    "darwin-arm64":
      "c06f54f06fb0abdac439204e7ceadab11962b888fa06377d31a37766b0b9550e",
    "darwin-x64-baseline":
      "40e43f7c44745236d5eeee62f520db7e038a99325eea174a0ad845585a6c8691",
    "linux-x64-baseline":
      "b7ca5951505515ff7ff23e6adabb9f09d1e2eec01bc6f52aabb8c5ff2ae6d356",
    "linux-arm64":
      "099bf525268245b875cf49357913c679092e60c1f85644b65c11b3d412b410f4",
  },
};
