// AUTOGENERATED by packages/release (bun run release:daemon) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored bundle outputs): this pins the
// published daemon release that the cloud's /api/daemon/binary route redirects
// to. Re-run `bun run release:daemon`, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release script run fills in the tag + checksums.

import type { TDaemonRelease } from "./release-types";

export const DAEMON_RELEASE: TDaemonRelease = {
  repo: "openllmsh/daemon",
  tag: "v1.7.21-cli.0",
  targets: [
    "darwin-arm64",
    "darwin-x64-baseline",
    "linux-x64-baseline",
    "linux-arm64",
  ],
  sha256: {
    "darwin-arm64":
      "731fcc697f86ffac7777f42a31d8a83e4b6516edff33771dbba1524f5e407067",
    "darwin-x64-baseline":
      "939e6fd3585aad699d1a3ac5fd9c1ba42d69158c5e33fc0829a2631eded04341",
    "linux-x64-baseline":
      "e707b09942ea82e1a16b7df9e501016111ca20579b4237168543517ba904ec71",
    "linux-arm64":
      "d30d583951ee231ca7d88774a069692223ba21cce2d42fb6c903c4566b265f79",
  },
};
