// AUTOGENERATED by packages/release (bun run release:daemon) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored bundle outputs): this pins the
// published daemon release that the cloud's /api/daemon/binary route redirects
// to. Re-run `bun run release:daemon`, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release script run fills in the tag + checksums.

import type { TDaemonRelease } from "./release-types";

export const DAEMON_RELEASE: TDaemonRelease = {
  repo: "openllmsh/daemon",
  tag: "v2.0.2-alpha.0",
  targets: [
    "darwin-arm64",
    "darwin-x64-baseline",
    "linux-x64-baseline",
    "linux-arm64",
  ],
  sha256: {
    "darwin-arm64":
      "f5d63a77090c855d90b9a498192f344c326f0d2c8bc03b484342ac2b23374a8a",
    "darwin-x64-baseline":
      "ef8af6b8a47186859d4c2449b56c78fc591598f158b47b594c80c3d36e1a6ca2",
    "linux-x64-baseline":
      "82f0f6bcc6eac8d3dcdc4f9db1cdf73a708a8044c77988b44799e44a4b815fde",
    "linux-arm64":
      "9ed3aa87e69ff069d22e9ff78f6a249365d0fcf6d472669ff5c0023e40273467",
  },
};
