#!/usr/bin/env bash
# ============================================================================
# OpenLLM daemon — self-contained installer for __TARGET__
# Auto-generated by `bun run daemon:dist` from local source (version __VERSION__).
# DO NOT EDIT — regenerate with: bun run daemon:dist
#
# This IS the upstream installer (packages/setup/daemon/install.sh) run VERBATIM,
# with the locally-built, gzipped daemon binary embedded at the end (base64).
# The ONLY change from a production install is transport: a tiny `curl` shim
# feeds the embedded binary + its sha256 to the unchanged download+verify step,
# so the binary needs no gateway/network. Every other step — checksum verify,
# install to ~/.openllm/bin, PATH symlink, the shared .env, macOS codesign,
# conditional daemon start, shell completion — runs EXACTLY as in production.
#
# Usage on a __TARGET__ machine (env names match the real install + the shared .env):
#   OPENLLM_CLOUD_ORIGIN=https://your-cloud OPENLLM_API_KEY=sk-llm-... bash "$0"
# Both are optional when ~/.openllm/.env already exists — its values are
# reused. OPENLLM_CLOUD_ORIGIN otherwise defaults to __CLOUD_DEFAULT__.
#
# NOTE: a dist install DISABLES daemon self-update by default, so a reachable
# cloud pinned to a different (or lower) release can't overwrite this locally-
# built binary — it's stamped with the app version, not the cloud's published
# daemon version. Re-enable by running with OPENLLM_DAEMON_AUTO_UPDATE=1, or
# later via `openllm auto-update on`.
# ============================================================================
set -euo pipefail

OPENLLMD_DIST_TARGET="__TARGET__"
OPENLLMD_DIST_SHA="__SHA__"

# --- guard: refuse the wrong-arch installer (the embedded binary wouldn't run) ---
_d_os=$(uname -s); _d_arch=$(uname -m)
case "$_d_os" in Darwin) _d_os=darwin ;; Linux) _d_os=linux ;; *) echo "Unsupported OS: $_d_os" >&2; exit 1 ;; esac
case "$_d_arch" in arm64|aarch64) _d_arch=arm64 ;; x86_64|amd64) _d_arch=x64-baseline ;; *) echo "Unsupported arch: $_d_arch" >&2; exit 1 ;; esac
if [ "${_d_os}-${_d_arch}" != "$OPENLLMD_DIST_TARGET" ]; then
  echo "This installer is built for ${OPENLLMD_DIST_TARGET}, but this machine is ${_d_os}-${_d_arch}." >&2
  echo "Copy openllmd-${_d_os}-${_d_arch}.install.sh to this machine instead." >&2
  exit 1
fi

# --- credential preflight ----------------------------------------------------
# Validate before extracting the embedded binary or making a staging directory.
# Bash values cannot contain NUL bytes; `$'\0'` expands to empty and would make
# a glob match every value, so only real line breaks need checking here.
_dist_has_line_break() { [[ "$1" == *$'\n'* || "$1" == *$'\r'* ]]; }
_dist_trim_whitespace() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}
_dist_is_minted_api_key() {
  [[ "$1" =~ ^sk-llm-[A-Za-z0-9_-]{14}[.][A-Za-z0-9_-]{43}$ ]]
}
OPENLLMD_DIST_ENV_FILE="${OPENLLM_DAEMON_ENV_FILE:-$HOME/.openllm/.env}"
# A custom env-file override must be absolute — the daemon + CLI only honour an
# absolute OPENLLM_DAEMON_ENV_FILE, so a relative value would write config the
# runtime never reads. Validate before the reuse read + staging directory below.
case "$OPENLLMD_DIST_ENV_FILE" in
  /*) ;;
  *) echo "Error: OPENLLM_DAEMON_ENV_FILE must be an absolute path" >&2; exit 1 ;;
esac
_openllmd_dist_reuse() {  # $1=key → its value in the existing env file (or "")
  [ -f "$OPENLLMD_DIST_ENV_FILE" ] || return 0
  grep -E "^$1=" "$OPENLLMD_DIST_ENV_FILE" 2>/dev/null | head -n1 | cut -d= -f2- || true
}
_dist_supplied_key="$(_dist_trim_whitespace "${OPENLLM_API_KEY:-}")"
if [ -n "$_dist_supplied_key" ]; then
  _dist_has_line_break "$_dist_supplied_key" && { echo "Error: OPENLLM_API_KEY must not contain a line break" >&2; exit 1; }
  _dist_is_minted_api_key "$_dist_supplied_key" || { echo "Error: OPENLLM_API_KEY has an invalid format" >&2; exit 1; }
  OPENLLM_API_KEY="$_dist_supplied_key"
fi
# The injected production installer re-reads this file while holding its lock.
# Do not turn a pre-download persisted key into a supplied key here: that would
# overwrite a concurrent re-pair with this stale snapshot.

# --- portable base64 decode (GNU '-d' vs BSD/macOS '-D') --------------------
if printf '' | base64 -d >/dev/null 2>&1; then _b64d=(base64 -d); else _b64d=(base64 -D); fi

# --- stage the embedded binary as a local 'gateway' payload -----------------
# Lay the binary + sha256 out at the SAME path shape the gateway serves
# (`/api/daemon/binary/<target>(.sha256)`) so the curl shim below can map a
# binary_url straight onto these files — install.sh stays byte-for-byte upstream.
OPENLLMD_DIST_WORK="$(mktemp -d)"
mkdir -p "$OPENLLMD_DIST_WORK/payload/api/daemon/binary" "$OPENLLMD_DIST_WORK/shim"
awk 'f{print} /^__OPENLLMD_GZ_BEGIN__$/{f=1}' "$0" | "${_b64d[@]}" \
  > "$OPENLLMD_DIST_WORK/payload/api/daemon/binary/$OPENLLMD_DIST_TARGET"
printf '%s  openllmd-%s\n' "$OPENLLMD_DIST_SHA" "$OPENLLMD_DIST_TARGET" \
  > "$OPENLLMD_DIST_WORK/payload/api/daemon/binary/$OPENLLMD_DIST_TARGET.sha256"

# --- curl shim: serve the embedded binary; pass anything else to real curl --
# install.sh only curls the binary + its .sha256 from $GATEWAY_ORIGIN; intercept
# exactly those (any URL containing /api/daemon/binary/) and copy from the local
# payload. Everything else (none, during install) falls through to the real curl
# resolved from the pre-shim PATH.
cat > "$OPENLLMD_DIST_WORK/shim/curl" <<'OPENLLMD_SHIM'
#!/usr/bin/env bash
real_curl="$(PATH="$OPENLLMD_DIST_REALPATH" command -v curl || true)"
url=""; out=""
args=("$@")
for ((i=0; i<${#args[@]}; i++)); do
  case "${args[$i]}" in
    -o) out="${args[$((i+1))]}" ;;
    http://*|https://*|file://*) url="${args[$i]}" ;;
  esac
done
if [[ "$url" == *"/api/daemon/binary/"* ]]; then
  rel="${url##*/api/daemon/binary/}"
  src="$OPENLLMD_DIST_PAYLOAD/api/daemon/binary/$rel"
  if [[ ! -f "$src" ]]; then echo "curl-shim: no embedded payload for $url" >&2; exit 22; fi
  if [[ -n "$out" ]]; then cp "$src" "$out"; else cat "$src"; fi
  exit 0
fi
if [[ -z "$real_curl" ]]; then echo "curl-shim: real curl not found (args: $*)" >&2; exit 127; fi
exec "$real_curl" "$@"
OPENLLMD_SHIM
chmod +x "$OPENLLMD_DIST_WORK/shim/curl"

export OPENLLMD_DIST_REALPATH="$PATH"
export OPENLLMD_DIST_PAYLOAD="$OPENLLMD_DIST_WORK/payload"
export PATH="$OPENLLMD_DIST_WORK/shim:$PATH"

# --- credentials: same OPENLLM_* names as the real install + the shared .env ---
# The production setup flow pipes the key as OPENLLM_API_KEY (the daemon's
# config_var) and the daemon boots from OPENLLM_CLOUD_ORIGIN; accept the SAME
# names here. Precedence:
#   1. an explicit OPENLLM_* value in the environment;
#   2. the value already in ~/.openllm/.env for the wrapper's cloud origin;
#   3. the baked default origin. The injected installer resolves the API key,
#      device id, and PTY preference under its lock immediately before writing.
if [ -f "$OPENLLMD_DIST_ENV_FILE" ]; then
  echo "Found existing $OPENLLMD_DIST_ENV_FILE — reusing its OPENLLM_CLOUD_ORIGIN + OPENLLM_API_KEY where not overridden." >&2
fi
OPENLLM_CLOUD_ORIGIN="${OPENLLM_CLOUD_ORIGIN:-$(_openllmd_dist_reuse OPENLLM_CLOUD_ORIGIN)}"
OPENLLM_CLOUD_ORIGIN="${OPENLLM_CLOUD_ORIGIN:-__CLOUD_DEFAULT__}"
export OPENLLM_CLOUD_ORIGIN
export USAGE_URL="${USAGE_URL:-}"
if [ -z "${OPENLLM_API_KEY:-}" ]; then
  echo "No API key was supplied; the installer will check the current config before starting the daemon." >&2
fi

# --- disable daemon self-update for this dist install (default) --------------
# A dist binary is stamped with the app's package.json version, NOT the cloud's
# published daemon release; if the reachable cloud is pinned to a different (or
# lower) version, the daemon's automatic self-update would OVERWRITE this just-
# installed local binary on its first tick. Default the opt-out and EXPORT it:
# the embedded installer's `openllmd start` persists OPENLLM_DAEMON_AUTO_UPDATE
# into the env file BEFORE the service first boots (see service.ts), so it's in
# effect before the first self-update check — no separate flag file. Opt back in
# by running with OPENLLM_DAEMON_AUTO_UPDATE=1.
export OPENLLM_DAEMON_AUTO_UPDATE="${OPENLLM_DAEMON_AUTO_UPDATE:-0}"
case "$OPENLLM_DAEMON_AUTO_UPDATE" in
  0 | false)
    echo "Daemon self-update DISABLED for this dist install (re-enable: openllm auto-update on)." >&2
    ;;
  *)
    echo "OPENLLM_DAEMON_AUTO_UPDATE=$OPENLLM_DAEMON_AUTO_UPDATE — leaving daemon self-update enabled." >&2
    ;;
esac

_openllmd_dist_cleanup() { rm -rf "$OPENLLMD_DIST_WORK"; }
trap _openllmd_dist_cleanup EXIT

# ======================= begin verbatim install.sh ==========================
__INSTALL_SH_BODY__
# ======================== end verbatim install.sh ===========================

# install.sh installs its OWN EXIT trap (for ITS temp files), replacing ours —
# so clean our staging dir explicitly now that it has completed successfully.
_openllmd_dist_cleanup
trap - EXIT
exit 0

__OPENLLMD_GZ_BEGIN__
__PAYLOAD_BASE64__
