import type {
  TImageEditRequest,
  TImageGenerationRequest,
  TImageGenerationResponse,
} from "@openllmsh/protocol";
import {
  base64ToBytes,
  ImageGenerationRequest,
  ImageGenerationResponse,
  normalizeContentType,
  parseImageEditInput,
} from "@openllmsh/protocol";
import { inspectImageBytes } from "@openllmsh/wire/lib/canonical/image-signature";
import { originatorHeadersFrom } from "@openllmsh/wire/lib/forwarded-headers";
import { Schema } from "effect";
import { uploadMedia } from "./cloud-client";
import { errorJson } from "./cors";
import { getDelegate, isSubscriptionSlug } from "./delegation";
import type { TImageCredential } from "./delegation/types";
import {
  buildImageEditUpstreamBody,
  ImageProviderUnavailableError,
  isSupportedImageEditReference,
} from "./image-edit-wire";
import { withMediaAttribution } from "./media-attribution";
import { forwardMediaHopToCloud } from "./media-cloud-forward";
import { mediaHopAdvances, mediaHttpErrorCode } from "./media-retry";
import type { TWalkArgs } from "./walker";
import {
  coolHopAfterStaleRefresh,
  parsePlan,
  passthroughHeaders,
  planSignatureOk,
  postUpstream,
  report,
  resolveHop,
  statusFor,
} from "./walker";

const parseImageRequest = Schema.decodeUnknownSync(ImageGenerationRequest);
const parseImageResponse = Schema.decodeUnknownSync(ImageGenerationResponse);

type TImageUpstream = {
  readonly headers: Record<string, string>;
  readonly url: string;
  readonly accountHash: string | null;
};

// `url` is optional: the b64-only fallback below (storage unavailable, caller
// explicitly asked for inline bytes) returns a data item with no hosted URL
// at all — never the vendor's own (possibly private/signed) URL, which this
// walker never forwards to the client in any code path.
type TImageDataItem = {
  readonly url?: string;
  readonly revised_prompt?: string;
  readonly b64_json?: string;
};

/** Runtime-agnostic bytes → base64 encoder (the inverse of `base64ToBytes`).
 *  The daemon already depends on `node:buffer`'s `Buffer` throughout
 *  (`keypair.ts`, `credential-gate.ts`, …), so this stays a plain local
 *  helper rather than a new protocol export. */
const bytesToBase64 = (bytes: ArrayBuffer | Uint8Array): string =>
  Buffer.from(
    bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes),
  ).toString("base64");

const toUint8Array = (bytes: ArrayBuffer | Uint8Array): Uint8Array =>
  bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);

export const persistImageDataItem = async (
  item: TImageGenerationResponse["data"][number],
  includeBase64: boolean,
  args: TWalkArgs,
): Promise<TImageDataItem> => {
  let bytes: ArrayBuffer | Uint8Array;
  let contentType = "image/png";

  if (item.b64_json !== undefined) {
    bytes = base64ToBytes(item.b64_json);
    // Sniff the real bytes rather than trusting the vendor's declared
    // format: a subscription bridge has been observed returning JPEG bytes
    // where the wire contract implied PNG (see
    // `wire/lib/canonical/image-signature.ts`). Unrecognized bytes keep the
    // historical "image/png" default — generation output that fails to
    // sniff is not necessarily malformed (a format `inspectImageBytes`
    // doesn't parse), so it is still persisted, just under the fallback
    // label it always used.
    const inspected = inspectImageBytes(bytes);
    if (inspected !== null) contentType = inspected.mime;
  } else if (item.url !== undefined && item.url.length > 0) {
    const image = await (args.fetchImpl ?? fetch)(item.url, {
      method: "GET",
      signal: AbortSignal.timeout(30_000),
    });
    if (!image.ok) {
      throw new Error("upstream image download failed");
    }
    contentType = normalizeContentType(
      image.headers.get("content-type"),
      "image/png",
    );
    bytes = await image.arrayBuffer();
  } else {
    throw new Error("image item has no content");
  }

  // `uploadMedia`'s own real implementation always resolves (never rejects —
  // it wraps every failure mode in its own try/catch and resolves `null`),
  // but the fallback below must reach the SAME decision no matter how a
  // caller's `uploadMedia` fails, including a bare rejection (a test double,
  // or any future implementation that stops honoring that contract) — so an
  // unexpected throw here degrades exactly like a `null` result instead of
  // surfacing as an unhandled rejection with a different, inconsistent shape.
  const saved = await uploadMedia(
    bytes,
    {
      contentType,
      kind: "image",
      sourceRef: undefined,
    },
    args.originParam,
  ).catch(() => null);

  if (saved === null) {
    // The media library is unreachable, but the vendor call already
    // succeeded and the generated bytes are sitting right here in memory.
    // When the caller explicitly asked for inline bytes
    // (`response_format: "b64_json"`), hand them back rather than
    // discarding a successful generation over a persistence concern the
    // caller never asked to depend on. A `url`-only caller has no
    // substitute for a hosted URL — that path still fails hard below
    // (strict URL-only failure, unchanged).
    if (includeBase64) {
      // Never fabricate media the sniffer can't positively identify as a
      // real image — a storage outage is not a license to hand back
      // malformed bytes just because the caller asked for base64.
      const inspected = inspectImageBytes(toUint8Array(bytes));
      if (inspected !== null) {
        return {
          // Reuse the vendor's own base64 when it already sent one;
          // otherwise (the item arrived as a `url`) encode the bytes this
          // walker itself downloaded — the vendor's URL (which may be
          // private/signed/time-limited) is never included here.
          b64_json: item.b64_json ?? bytesToBase64(bytes),
          ...(item.revised_prompt !== undefined
            ? { revised_prompt: item.revised_prompt }
            : {}),
        };
      }
    }
    throw new Error("failed to upload image");
  }
  return {
    url: saved.url,
    ...(includeBase64 && item.b64_json !== undefined
      ? { b64_json: item.b64_json }
      : {}),
    ...(item.revised_prompt !== undefined
      ? { revised_prompt: item.revised_prompt }
      : {}),
  };
};

export const acquireImageUpstream = async (
  provider: string,
  args: TWalkArgs,
  hop: { readonly provider: string; readonly modelId: string },
  walkSessionKey?: string,
): Promise<TImageUpstream | "retry"> => {
  const delegate = getDelegate(provider);
  if (delegate?.credentialForImage === undefined) return "retry";
  try {
    const cred = await delegate.credentialForImage(args.req.headers);
    if (cred.stale_refresh !== undefined) {
      coolHopAfterStaleRefresh(hop, cred.stale_refresh, walkSessionKey);
      return "retry";
    }
    return {
      headers: {
        ...originatorHeadersFrom(args.req.headers),
        ...cred.headers,
        authorization: `Bearer ${cred.access_token}`,
      },
      url: cred.url,
      accountHash: cred.account_hash ?? null,
    };
  } catch {
    return "retry";
  }
};

export const sizeToAspect = (size?: string): string => {
  switch (size) {
    case "1792x1024":
      return "16:9";
    case "1024x1792":
      return "9:16";
    case undefined:
    case "1024x1024":
      return "1:1";
    case "auto":
      return "auto";
    default: {
      const dimensions = /^(\d+)x(\d+)$/.exec(size);
      const width = Number(dimensions?.[1]);
      const height = Number(dimensions?.[2]);
      if (
        !Number.isSafeInteger(width) ||
        !Number.isSafeInteger(height) ||
        width <= 0 ||
        height <= 0
      )
        throw new Error("Grok image size is not supported by this transport");
      const gcd = (a: number, b: number): number =>
        b === 0 ? a : gcd(b, a % b);
      const divisor = gcd(width, height);
      return `${width / divisor}:${height / divisor}`;
    }
  }
};

export const buildImageUpstreamBody = (
  provider: string,
  req: TImageGenerationRequest,
  providerModelId: string,
): Record<string, unknown> => {
  if (provider === "chatgpt") {
    // Forward the `gpt-image`-supported options so client settings aren't
    // silently dropped. `style` + `response_format` are DALL·E-era params that
    // gpt-image (what Codex serves) rejects — forwarding them would 400, so
    // they're intentionally omitted (gpt-image always returns b64_json).
    return {
      model: providerModelId,
      prompt: req.prompt,
      ...(req.n !== undefined ? { n: req.n } : {}),
      ...(req.size !== undefined ? { size: req.size } : {}),
      ...(req.quality !== undefined ? { quality: req.quality } : {}),
      ...(req.background !== undefined ? { background: req.background } : {}),
      ...(req.user !== undefined ? { user: req.user } : {}),
    };
  }
  if (provider === "grok") {
    const unmapped =
      req.style !== undefined
        ? "style"
        : req.background !== undefined
          ? "background"
          : req.user !== undefined
            ? "user"
            : undefined;
    if (unmapped !== undefined)
      throw new Error(
        `Grok image adapter cannot map ${unmapped}; it was not discarded. Use an image adapter that serializes this option, or remove it only if it is not intended.`,
      );
    return {
      model: providerModelId,
      ...(req.quality !== undefined ? { quality: req.quality } : {}),
      prompt: req.prompt,
      n: req.n ?? 1,
      aspect_ratio: sizeToAspect(req.size),
      resolution: "1k",
      response_format: "b64_json",
    };
  }
  throw new ImageProviderUnavailableError(
    `Unsupported subscription image provider: ${provider}`,
  );
};

export const normalizeImageResponse = (
  upstream: unknown,
): TImageGenerationResponse => {
  const data =
    upstream !== null && typeof upstream === "object"
      ? (upstream as { readonly data?: unknown }).data
      : undefined;
  // A "success" upstream body with no `data` array is malformed — surface it
  // as a 502 (the caller converts this throw) rather than fabricating an empty
  // but 200-OK image response the client would read as a successful no-op.
  if (!Array.isArray(data)) {
    throw new Error("upstream image response missing a data array");
  }
  return parseImageResponse({
    created: Math.floor(Date.now() / 1000),
    data,
  });
};

export const runImageWalker = async (args: TWalkArgs): Promise<Response> => {
  if (
    !planSignatureOk(
      args.planParam,
      args.pmidsParam,
      args.originParam,
      args.contextOverflowStrategy ?? null,
      args.sigParam,
    )
  ) {
    return errorJson(403, "invalid or missing __plan signature");
  }
  if (args.planParam === null) {
    return errorJson(400, "images require a daemon plan");
  }

  let imageRequest: TImageGenerationRequest;
  try {
    imageRequest = parseImageRequest(args.rawBody);
  } catch (err) {
    return errorJson(
      400,
      err instanceof Error ? err.message : "Invalid image generation request",
    );
  }

  const pmids = args.pmidsParam === null ? [] : args.pmidsParam.split(",");
  const hops = parsePlan(args.planParam).map((modelId, index) =>
    resolveHop(modelId, pmids[index]),
  );
  const attempted: string[] = [];
  const stamp = (resp: Response, resolved?: string): Response =>
    withMediaAttribution(resp, {
      attempted,
      ...(resolved !== undefined ? { resolvedModel: resolved } : {}),
    });

  let lastError: Response | null = null;
  for (let i = 0; i < hops.length; i++) {
    const hop = hops[i];
    if (hop === undefined) continue;
    const last = i === hops.length - 1;
    if (isSubscriptionSlug(hop.provider)) {
      // Validate before credential fallback can advance to an unchecked transport.
      let upstreamBody: Record<string, unknown>;
      try {
        upstreamBody = buildImageUpstreamBody(
          hop.provider,
          imageRequest,
          hop.providerModelId,
        );
      } catch (err) {
        const errorCode =
          err instanceof ImageProviderUnavailableError
            ? "model_unavailable"
            : "caller_error";
        lastError = errorJson(
          400,
          err instanceof Error ? err.message : "Invalid image request",
          errorCode,
        );
        if (!last && mediaHopAdvances({ dispatched: false, errorCode }))
          continue;
        return stamp(lastError);
      }
      const delegate = getDelegate(hop.provider);
      if (delegate?.credentialForImage === undefined) {
        if (
          !last &&
          mediaHopAdvances({
            dispatched: false,
            errorCode: "missing_credential",
          })
        ) {
          continue;
        }
        return stamp(
          errorJson(404, `No image credential available for ${hop.provider}`),
        );
      }
      const acquired = await acquireImageUpstream(hop.provider, args, hop);
      if (acquired === "retry") {
        if (
          !last &&
          mediaHopAdvances({
            dispatched: false,
            errorCode: "missing_credential",
          })
        )
          continue;
        return stamp(
          errorJson(404, `No image credential available for ${hop.provider}`),
        );
      }
      attempted.push(hop.modelId);

      const resp = await postUpstream(acquired.url, {
        method: "POST",
        headers: {
          ...acquired.headers,
          "content-type": "application/json",
          accept: "application/json",
        },
        body: JSON.stringify(upstreamBody),
        signal: args.req.signal,
      });
      if (resp === null) {
        const terminal = args.req.signal.aborted
          ? errorJson(499, "client aborted request")
          : errorJson(502, "upstream image provider is unreachable");
        return stamp(terminal);
      }
      if (!resp.ok) {
        const body = await resp.text().catch(() => "");
        report(
          {
            model: hop.modelId,
            provider: hop.provider,
            status: statusFor(resp.status),
            tokens_in: 0,
            tokens_out: 0,
            latency_ms: Date.now() - args.startedAt,
            endpoint: args.endpoint,
            ...(acquired.accountHash !== null
              ? { account_hash: acquired.accountHash }
              : {}),
          },
          args.originParam,
        );
        lastError = new Response(body.length > 0 ? body : null, {
          status: resp.status,
          headers: passthroughHeaders(resp),
        });
        if (
          !last &&
          mediaHopAdvances({
            dispatched: true,
            httpStatus: resp.status,
            errorCode: mediaHttpErrorCode(resp.status),
            accepted: false,
          })
        ) {
          continue;
        }
        return stamp(lastError);
      }
      let upstream: unknown;
      try {
        upstream = await resp.json();
      } catch {
        return stamp(
          errorJson(502, "upstream image provider returned invalid JSON"),
        );
      }
      let normalized: TImageGenerationResponse;
      try {
        normalized = normalizeImageResponse(upstream);
      } catch (err) {
        return stamp(
          errorJson(
            502,
            err instanceof Error
              ? `upstream image provider returned invalid data: ${err.message}`
              : "upstream image provider returned invalid data",
          ),
        );
      }
      const includeBase64 = imageRequest.response_format === "b64_json";
      let persistedItems: ReadonlyArray<TImageDataItem>;
      try {
        persistedItems = await Promise.all(
          normalized.data.map((item) =>
            persistImageDataItem(item, includeBase64, args),
          ),
        );
      } catch {
        return stamp(errorJson(502, "Failed to persist generated image"));
      }
      report(
        {
          model: hop.modelId,
          provider: hop.provider,
          status: statusFor(resp.status),
          tokens_in: 0,
          tokens_out: 0,
          latency_ms: Date.now() - args.startedAt,
          endpoint: args.endpoint,
          ...(acquired.accountHash !== null
            ? { account_hash: acquired.accountHash }
            : {}),
        },
        args.originParam,
      );
      return stamp(
        new Response(JSON.stringify({ ...normalized, data: persistedItems }), {
          status: 200,
          headers: { "content-type": "application/json" },
        }),
        hop.modelId,
      );
    }
    attempted.push(hop.modelId);
    const forwarded = await forwardMediaHopToCloud(args, hop.modelId);
    if (forwarded.ok) {
      return stamp(forwarded, hop.modelId);
    }
    lastError = forwarded;
    if (
      !last &&
      mediaHopAdvances({
        dispatched: true,
        httpStatus: forwarded.status,
        errorCode: mediaHttpErrorCode(forwarded.status),
        accepted: false,
      })
    ) {
      continue;
    }
    return stamp(forwarded);
  }
  return stamp(
    lastError ??
      errorJson(
        404,
        "No image provider in the daemon plan can serve this request",
      ),
  );
};

// ─── Image EDITS ───────────────────────────────────────────────────────────
//
// A distinct entry point (`runImageEditWalker`) rather than a branch inside
// `runImageWalker`: edits have their own request shape (single reference
// image, no `style`/`background`, masks explicitly rejected — see
// `@openllmsh/protocol/image-edit-parse`), their own upstream wire per
// provider (`buildImageEditUpstreamBody`), and — critically — they must
// NEVER silently fall back to generation when a provider/credential is
// missing.

// `url` is optional for the same reason as `TImageDataItem` above: the
// b64-only storage-outage fallback never has (or fabricates) a hosted URL.
type TImageEditDataItem = {
  readonly url?: string;
  readonly b64_json?: string;
};

/**
 * Acquire the local credential for ONE subscription provider's image-EDIT
 * endpoint. Mirrors {@link acquireImageUpstream} but reads
 * `credentialForImageEdit` — a distinct delegate method so a provider can
 * target `/images/edits` without reusing its generation URL/headers.
 */
export const acquireImageEditUpstream = async (
  provider: string,
  args: TWalkArgs,
  hop: { readonly provider: string; readonly modelId: string },
  walkSessionKey?: string,
): Promise<TImageUpstream | "retry"> => {
  const delegate = getDelegate(provider);
  if (delegate?.credentialForImageEdit === undefined) return "retry";
  try {
    const cred: TImageCredential = await delegate.credentialForImageEdit(
      args.req.headers,
    );
    if (cred.stale_refresh !== undefined) {
      coolHopAfterStaleRefresh(hop, cred.stale_refresh, walkSessionKey);
      return "retry";
    }
    return {
      headers: {
        ...originatorHeadersFrom(args.req.headers),
        ...cred.headers,
        authorization: `Bearer ${cred.access_token}`,
      },
      url: cred.url,
      accountHash: cred.account_hash ?? null,
    };
  } catch {
    return "retry";
  }
};

/** Decode the base64 payload out of a `data:...;base64,<payload>` URL. */
const bytesFromDataUrl = (url: string): Uint8Array => {
  const comma = url.indexOf(",");
  return base64ToBytes(comma === -1 ? "" : url.slice(comma + 1));
};

/**
 * Persist ONE edit-result image. Unlike generation's `persistImageDataItem`,
 * a result whose bytes don't sniff as a real image is REJECTED rather than
 * stored under a fallback MIME: an edit endpoint returning garbage (or a
 * truncated/corrupted payload) is a malformed provider result, and this is
 * a brand-new persistence path with no legacy behavior to preserve.
 */
export const persistImageEditResultItem = async (
  item: { readonly url?: string; readonly b64_json?: string },
  includeBase64: boolean,
  args: TWalkArgs,
): Promise<TImageEditDataItem> => {
  let bytes: Uint8Array;
  if (item.b64_json !== undefined) {
    bytes = base64ToBytes(item.b64_json);
  } else if (item.url !== undefined && item.url.length > 0) {
    // Every edit upstream this daemon knows (`buildImageEditUpstreamBody`)
    // requests `response_format: "b64_json"` / an inline `image_url`; a
    // provider answering with a bare `https://` result would mean fetching
    // a vendor-controlled URL this box cannot SSRF-vet. Only an inline
    // `data:` result is accepted.
    if (!isSupportedImageEditReference(item.url)) {
      throw new Error(
        "upstream image edit returned a fetchable URL result, which this daemon does not fetch",
      );
    }
    bytes = bytesFromDataUrl(item.url);
  } else {
    throw new Error("image edit result has no content");
  }

  const inspected = inspectImageBytes(bytes);
  if (inspected === null) {
    throw new Error("upstream image edit returned unrecognized image bytes");
  }

  // Same rejection-vs-null note as generation's `persistImageDataItem`
  // above: `uploadMedia` should never reject in production, but a caller
  // that does reject must degrade the same way a `null` resolution does.
  const saved = await uploadMedia(
    bytes,
    { contentType: inspected.mime, kind: "image", sourceRef: undefined },
    args.originParam,
  ).catch(() => null);
  if (saved === null) {
    // Same storage-outage fallback as generation's `persistImageDataItem`:
    // the edit result is already sniffed as a real image above (unlike
    // generation, edits never tolerate an unrecognized-format fallback), so
    // handing it back inline for an explicit b64_json request is safe. A
    // `url`-only caller still fails hard — there is no hosted URL to give it.
    if (includeBase64) {
      return {
        b64_json: item.b64_json ?? bytesToBase64(bytes),
      };
    }
    throw new Error("failed to upload edited image");
  }
  return {
    url: saved.url,
    ...(includeBase64 && item.b64_json !== undefined
      ? { b64_json: item.b64_json }
      : {}),
  };
};

/**
 * Walk one image-EDIT request. Same 403/400 plan gate as {@link runImageWalker}.
 * The plan candidate must be a subscription provider whose delegate exposes
 * `credentialForImageEdit` — an API-key (BYOK) hop is never considered here;
 * the cloud handler is responsible for refusing BYOK explicitly rather than
 * ever 307ing one to this walker.
 */
export const runImageEditWalker = async (
  args: TWalkArgs,
): Promise<Response> => {
  if (
    !planSignatureOk(
      args.planParam,
      args.pmidsParam,
      args.originParam,
      args.contextOverflowStrategy ?? null,
      args.sigParam,
    )
  ) {
    return errorJson(403, "invalid or missing __plan signature");
  }
  if (args.planParam === null) {
    return errorJson(400, "image edits require a daemon plan");
  }

  // The listener (`listener.ts`) already normalized this request once: a
  // JSON body goes straight through `parseImageEditInput`, and a multipart
  // upload is flattened by `parseImageEditMultipart` into the same shape
  // first — either way, `args.rawBody` here is that already-decoded
  // `TImageEditRequest`, not the original wire body. This is therefore a
  // SECOND, safe pass over the listener's own output: re-running the same
  // pure parser on its already-canonical shape is idempotent (no
  // `mask`/`style`/`background` survive the first pass, and `image` is
  // already `{ url }`), so it can't reject a request the listener accepted.
  // It exists so this walker never trusts an upstream cast without
  // re-validating against the one parser that owns the contract.
  const parsed = parseImageEditInput(args.rawBody);
  if (!parsed.ok) {
    return errorJson(400, parsed.error.message, parsed.error.code);
  }
  const editRequest: TImageEditRequest = parsed.request;

  if (!isSupportedImageEditReference(editRequest.image.url)) {
    return errorJson(
      400,
      "Image edits accept only an inline (data:) image upload in this release — remote image URLs are not supported.",
      "image_edit_remote_url_unsupported",
    );
  }

  const pmids = args.pmidsParam === null ? [] : args.pmidsParam.split(",");
  const hops = parsePlan(args.planParam).map((modelId, index) =>
    resolveHop(modelId, pmids[index]),
  );
  const attempted: string[] = [];
  const stamp = (resp: Response, resolved?: string): Response =>
    withMediaAttribution(resp, {
      attempted,
      ...(resolved !== undefined ? { resolvedModel: resolved } : {}),
    });

  let lastError: Response | null = null;
  for (let i = 0; i < hops.length; i++) {
    const hop = hops[i];
    if (hop === undefined) continue;
    const last = i === hops.length - 1;
    if (!isSubscriptionSlug(hop.provider)) {
      continue;
    }
    // Invalid caller options are terminal, even when this hop lacks credentials.
    let upstreamBody: Record<string, unknown>;
    try {
      upstreamBody = buildImageEditUpstreamBody(
        hop.provider,
        editRequest,
        hop.providerModelId,
      );
    } catch (err) {
      const errorCode =
        err instanceof ImageProviderUnavailableError
          ? "model_unavailable"
          : "caller_error";
      lastError = errorJson(
        400,
        err instanceof Error ? err.message : "Invalid image-edit request",
        errorCode,
      );
      if (!last && mediaHopAdvances({ dispatched: false, errorCode })) continue;
      return stamp(lastError);
    }
    const acquired = await acquireImageEditUpstream(hop.provider, args, hop);
    if (acquired === "retry") {
      if (
        !last &&
        mediaHopAdvances({
          dispatched: false,
          errorCode: "missing_credential",
        })
      )
        continue;
      return stamp(
        errorJson(
          404,
          `No image-edit credential available for ${hop.provider}`,
        ),
      );
    }
    attempted.push(hop.modelId);
    const resp = await postUpstream(acquired.url, {
      method: "POST",
      headers: {
        ...acquired.headers,
        "content-type": "application/json",
        accept: "application/json",
      },
      body: JSON.stringify(upstreamBody),
      signal: args.req.signal,
    });
    if (resp === null) {
      return stamp(
        args.req.signal.aborted
          ? errorJson(499, "client aborted request")
          : errorJson(502, "upstream image-edit provider is unreachable"),
      );
    }
    if (!resp.ok) {
      const body = await resp.text().catch(() => "");
      report(
        {
          model: hop.modelId,
          provider: hop.provider,
          status: statusFor(resp.status),
          tokens_in: 0,
          tokens_out: 0,
          latency_ms: Date.now() - args.startedAt,
          endpoint: args.endpoint,
          ...(acquired.accountHash !== null
            ? { account_hash: acquired.accountHash }
            : {}),
        },
        args.originParam,
      );
      lastError = new Response(body.length > 0 ? body : null, {
        status: resp.status,
        headers: passthroughHeaders(resp),
      });
      if (
        !last &&
        mediaHopAdvances({
          dispatched: true,
          httpStatus: resp.status,
          errorCode: mediaHttpErrorCode(resp.status),
          accepted: false,
        })
      ) {
        continue;
      }
      return stamp(lastError);
    }
    let upstream: unknown;
    try {
      upstream = await resp.json();
    } catch {
      return stamp(
        errorJson(502, "upstream image-edit provider returned invalid JSON"),
      );
    }
    let normalized: TImageGenerationResponse;
    try {
      normalized = normalizeImageResponse(upstream);
    } catch (err) {
      return stamp(
        errorJson(
          502,
          err instanceof Error
            ? `upstream image-edit provider returned invalid data: ${err.message}`
            : "upstream image-edit provider returned invalid data",
        ),
      );
    }
    const includeBase64 = editRequest.response_format === "b64_json";
    let persistedItems: ReadonlyArray<TImageEditDataItem>;
    try {
      persistedItems = await Promise.all(
        normalized.data.map((item) =>
          persistImageEditResultItem(item, includeBase64, args),
        ),
      );
    } catch {
      return stamp(errorJson(502, "Failed to persist edited image"));
    }
    report(
      {
        model: hop.modelId,
        provider: hop.provider,
        status: statusFor(resp.status),
        tokens_in: 0,
        tokens_out: 0,
        latency_ms: Date.now() - args.startedAt,
        endpoint: args.endpoint,
        ...(acquired.accountHash !== null
          ? { account_hash: acquired.accountHash }
          : {}),
      },
      args.originParam,
    );
    return stamp(
      new Response(JSON.stringify({ ...normalized, data: persistedItems }), {
        status: 200,
        headers: { "content-type": "application/json" },
      }),
      hop.modelId,
    );
  }
  return stamp(
    lastError ??
      errorJson(
        404,
        "No subscription image-edit provider in the daemon plan can serve this request",
      ),
  );
};
